version: '3'
services:
  app:
    container_name: project-euler-node-server
    restart: always
    build: .
    ports:
      - '3131:3131'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'